# Generated by Django 5.1.4 on 2025-01-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=15)),
                ('no_nd', models.CharField(max_length=15)),
                ('tgl_nd', models.DateField()),
                ('nama', models.CharField(max_length=15)),
                ('nip', models.CharField(max_length=16)),
                ('jabatan', models.CharField(max_length=15)),
                ('jns_data', models.CharField(max_length=15)),
                ('uraian', models.CharField(max_length=15)),
            ],
        ),
    ]
